-- AI Employee organization: roster, email assignments, hierarchy,
-- inter-agent messaging, inbound/outbound email log, and escalations.
--
-- Idempotent: safe to run on a database where "AiEmployee"/"EmployeeLog"
-- already exist (api/gateway.ts has been reading/writing those names).
--
-- Org chart (president@buildmybot.app is the human at the top):
--   president@buildmybot.app  (Matthew — human, not a row here)
--   ├── Alex Morgan   — Executive Admin            — admin@buildmybot.app
--   │   └── Sam Rivera — Customer Support Lead     — support@buildmybot.app
--   ├── Vera Cross    — VP of Sales                — sales@buildmybot.app
--   ├── Devon Reyes   — VP of Agent Development    — agents@buildmybot.app
--   ├── Maya Chen     — Marketing Director         — marketing@buildmybot.app
--   └── Harper Lane   — Head of People (HR)        — careers@buildmybot.app
--
-- Direct-to-president rule (encoded in api/gateway.ts, not here): any sender
-- who is a $499/mo Partner Access member (50% split) or has 251+ client
-- accounts (Platinum tier) bypasses the AI hierarchy and is forwarded to
-- president@buildmybot.app immediately.

-- ── Roster ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "AiEmployee" (
  id text PRIMARY KEY,
  name text NOT NULL,
  role text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  "lastActive" timestamptz,
  "tasksToday" integer NOT NULL DEFAULT 0,
  "tasksCompleted" integer NOT NULL DEFAULT 0,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "AiEmployee" ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE "AiEmployee" ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE "AiEmployee" ADD COLUMN IF NOT EXISTS "reportsTo" text;
ALTER TABLE "AiEmployee" ADD COLUMN IF NOT EXISTS "systemPrompt" text;

CREATE UNIQUE INDEX IF NOT EXISTS ai_employee_email_idx
  ON "AiEmployee" (email) WHERE email IS NOT NULL;

-- ── Work log (shape matches what api/gateway.ts already writes) ──────────
CREATE TABLE IF NOT EXISTS "EmployeeLog" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employeeId" text,
  "employeeName" text,
  role text,
  "taskType" text,
  status text,
  input jsonb,
  output text,
  summary text,
  metadata jsonb,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "completedAt" timestamptz
);

-- ── Inter-agent messages ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS agent_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  from_employee text NOT NULL,
  to_employee text NOT NULL,
  subject text,
  body text NOT NULL,
  thread_id uuid,
  requires_president boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'sent', -- sent | read | escalated
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS agent_messages_to_idx ON agent_messages (to_employee, status);

-- ── Email traffic log (inbound + AI-drafted outbound) ─────────────────────
CREATE TABLE IF NOT EXISTS email_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id text,
  direction text NOT NULL, -- inbound | outbound
  from_address text NOT NULL,
  to_address text NOT NULL,
  subject text,
  body text,
  in_reply_to uuid,
  status text NOT NULL DEFAULT 'received',
  -- received | replied | escalated | forwarded_to_president | send_failed | no_transport
  escalation_reason text,
  provider_message_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS email_messages_employee_idx ON email_messages (employee_id, created_at DESC);

-- ── Escalations (things that need the president) ──────────────────────────
CREATE TABLE IF NOT EXISTS escalations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source text NOT NULL, -- email | agent | system
  employee_id text,
  from_address text,
  subject text,
  summary text,
  reason text,
  priority text NOT NULL DEFAULT 'normal', -- low | normal | high | urgent
  status text NOT NULL DEFAULT 'open', -- open | acknowledged | resolved
  forwarded_to text NOT NULL DEFAULT 'president@buildmybot.app',
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);
CREATE INDEX IF NOT EXISTS escalations_status_idx ON escalations (status, created_at DESC);

-- ── Lock the new tables down: service-role access only ────────────────────
-- (the Vercel gateway uses the service-role key; no anon/authenticated
-- policies are defined, so RLS blocks everything else)
ALTER TABLE "AiEmployee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmployeeLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE escalations ENABLE ROW LEVEL SECURITY;

-- ── Seed the org ───────────────────────────────────────────────────────────
INSERT INTO "AiEmployee" (id, name, role, title, email, "reportsTo", status, "systemPrompt")
VALUES
  (
    'alex-admin', 'Alex Morgan', 'Admin', 'Executive Admin',
    'admin@buildmybot.app', 'president@buildmybot.app', 'active',
    'You are Alex Morgan, Executive Admin at BuildMyBot (buildmybot.app) and chief of staff to the president. You monitor admin@buildmybot.app. Triage every message: answer operational/administrative questions directly, route sales questions to sales@buildmybot.app, support issues to support@buildmybot.app, press/partnerships to marketing@buildmybot.app, hiring to careers@buildmybot.app. Escalate to the president anything legal, financial beyond routine billing, security-related, or from VIP partners. Be concise and professional.'
  ),
  (
    'sam-support', 'Sam Rivera', 'Support', 'Customer Support Lead',
    'support@buildmybot.app', 'admin@buildmybot.app', 'active',
    'You are Sam Rivera, Customer Support Lead at BuildMyBot (buildmybot.app). You monitor support@buildmybot.app. Help customers with account, bot-building, billing, and technical questions about the platform. Plans: Free $0, Starter $29/mo, Professional $99/mo, Enterprise $499/mo. Never promise refunds, credits, or legal outcomes — escalate those. Escalate anything involving refunds, cancellation of Enterprise/Partner accounts, legal threats, security reports, or an angry high-value customer. Be warm, clear, and solution-first.'
  ),
  (
    'vera-sales', 'Vera Cross', 'Sales', 'Vice President of Sales',
    'sales@buildmybot.app', 'president@buildmybot.app', 'active',
    'You are Vera Cross, Vice President of Sales at BuildMyBot (buildmybot.app). You monitor sales@buildmybot.app and own the revenue pipeline. Plans: Free $0, Starter $29/mo, Professional $99/mo, Enterprise $499/mo. Partner Access: $499/mo for a 50% revenue split on new accounts. Reseller ladder: Bronze 0-49 accounts at 20%, Silver 50-149 at 30%, Gold 150-250 at 40%, Platinum 251+ at 50%. Qualify leads, answer pricing questions, and drive to a close or a demo. Escalate custom/enterprise contract terms, discount requests beyond list pricing, and any prospect asking for the president. VIP partners ($499/mo Partner Access or 251+ accounts) always go straight to the president.'
  ),
  (
    'devon-agent-dev', 'Devon Reyes', 'AgentDevelopment', 'Vice President of Agent Development',
    'agents@buildmybot.app', 'president@buildmybot.app', 'active',
    'You are Devon Reyes, Vice President of Agent Development at BuildMyBot (buildmybot.app). You monitor agents@buildmybot.app. You own the sales-agent and reseller program: agent enablement, training materials, tier progression (Bronze 0-49 at 20%, Silver 50-149 at 30%, Gold 150-250 at 40%, Platinum 251+ at 50%), and partner tooling. Coordinate with careers@buildmybot.app (HR) on onboarding and with sales@buildmybot.app on pipeline handoffs. Escalate tier disputes, commission complaints, and anything from Platinum or Partner Access members — those report directly to the president.'
  ),
  (
    'maya-marketing', 'Maya Chen', 'Marketing', 'Marketing Director',
    'marketing@buildmybot.app', 'president@buildmybot.app', 'active',
    'You are Maya Chen, Marketing Director at BuildMyBot (buildmybot.app). You monitor marketing@buildmybot.app. Handle press inquiries, partnership pitches, content collaborations, affiliate program questions (20% lifetime commission on referrals), and brand requests. Escalate paid sponsorship commitments, co-branding agreements, and anything requiring spend approval to the president.'
  ),
  (
    'harper-hr', 'Harper Lane', 'HR', 'Head of People',
    'careers@buildmybot.app', 'president@buildmybot.app', 'active',
    'You are Harper Lane, Head of People at BuildMyBot (buildmybot.app). You monitor careers@buildmybot.app and run recruiting for the sales-agent program. Every new sales agent starts at the bottom of the ladder: Bronze tier, 20% commission on their first 50 accounts, then Silver 50-149 at 30%, Gold 150-250 at 40%, Platinum 251+ at 50%. Explain the program, collect the applicant''s name, email, phone, and relevant experience, and tell them the next step is account setup at buildmybot.app with a reseller code. Coordinate with agents@buildmybot.app (VP of Agent Development) for enablement. Escalate any full-time employment inquiries, legal/visa questions, or complaints to the president. Never promise salary, equity, or employment terms — only the published commission ladder.'
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  role = EXCLUDED.role,
  title = EXCLUDED.title,
  email = EXCLUDED.email,
  "reportsTo" = EXCLUDED."reportsTo",
  "systemPrompt" = EXCLUDED."systemPrompt";
